'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ResourcesLang
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("inoPBI.ResourcesLang", GetType(ResourcesLang).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnCancel() As String
            Get
                Return ResourceManager.GetString("BtnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnClose() As String
            Get
                Return ResourceManager.GetString("BtnClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Create Documentation ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnCreateDokumentation() As String
            Get
                Return ResourceManager.GetString("BtnCreateDokumentation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Create PDF ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnCreatePDF() As String
            Get
                Return ResourceManager.GetString("BtnCreatePDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Delete entry ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnDeleteEntry() As String
            Get
                Return ResourceManager.GetString("BtnDeleteEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Down ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnDown() As String
            Get
                Return ResourceManager.GetString("BtnDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnEdit() As String
            Get
                Return ResourceManager.GetString("BtnEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die New project ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnNewProject() As String
            Get
                Return ResourceManager.GetString("BtnNewProject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnOK() As String
            Get
                Return ResourceManager.GetString("BtnOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnOpen() As String
            Get
                Return ResourceManager.GetString("BtnOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Refresh ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnRefresh() As String
            Get
                Return ResourceManager.GetString("BtnRefresh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rename project ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnRenameProject() As String
            Get
                Return ResourceManager.GetString("BtnRenameProject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Replace ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnReplace() As String
            Get
                Return ResourceManager.GetString("BtnReplace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnSave() As String
            Get
                Return ResourceManager.GetString("BtnSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Save as ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnSaveAs() As String
            Get
                Return ResourceManager.GetString("BtnSaveAs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Select project ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnSelectProject() As String
            Get
                Return ResourceManager.GetString("BtnSelectProject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Up ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnUp() As String
            Get
                Return ResourceManager.GetString("BtnUp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Edit file {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property HtmlEditTitle() As String
            Get
                Return ResourceManager.GetString("HtmlEditTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Edit HTML file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property HtmlTitle() As String
            Get
                Return ResourceManager.GetString("HtmlTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Copyright  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InfoCopyright() As String
            Get
                Return ResourceManager.GetString("InfoCopyright", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Info {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InfoTitle() As String
            Get
                Return ResourceManager.GetString("InfoTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Version {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InfoVersion() As String
            Get
                Return ResourceManager.GetString("InfoVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Current project: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainTslCurrentProject() As String
            Get
                Return ResourceManager.GetString("MainTslCurrentProject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hint ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgHint() As String
            Get
                Return ResourceManager.GetString("MsgHint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No file given. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgNoFileGiven() As String
            Get
                Return ResourceManager.GetString("MsgNoFileGiven", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nothing selected ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgNothingSelected() As String
            Get
                Return ResourceManager.GetString("MsgNothingSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die PDF file in use. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgPdfFileInUse() As String
            Get
                Return ResourceManager.GetString("MsgPdfFileInUse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Something went wrong ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgSomethingWentWrong() As String
            Get
                Return ResourceManager.GetString("MsgSomethingWentWrong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Measure ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MUMeasure() As String
            Get
                Return ResourceManager.GetString("MUMeasure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MUName() As String
            Get
                Return ResourceManager.GetString("MUName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Page ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MUPage() As String
            Get
                Return ResourceManager.GetString("MUPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Table ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MUTable() As String
            Get
                Return ResourceManager.GetString("MUTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Measure usage ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MUTitle() As String
            Get
                Return ResourceManager.GetString("MUTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Usage ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MUUsage() As String
            Get
                Return ResourceManager.GetString("MUUsage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Documentation export finished ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfDocumentationExportFinished() As String
            Get
                Return ResourceManager.GetString("PdfDocumentationExportFinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Documentation export to pdf ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfDocumentationExportToPdf() As String
            Get
                Return ResourceManager.GetString("PdfDocumentationExportToPdf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Documentation file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfDocumentationFile() As String
            Get
                Return ResourceManager.GetString("PdfDocumentationFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Document title ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfDocumentTitle() As String
            Get
                Return ResourceManager.GetString("PdfDocumentTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Footer HTML file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfFooterFile() As String
            Get
                Return ResourceManager.GetString("PdfFooterFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Header HTML file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfHeaderFile() As String
            Get
                Return ResourceManager.GetString("PdfHeaderFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Select Footer File ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfSelectFooterFile() As String
            Get
                Return ResourceManager.GetString("PdfSelectFooterFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Select Header file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfSelectHeaderFile() As String
            Get
                Return ResourceManager.GetString("PdfSelectHeaderFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Show PDF file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfShowPDF() As String
            Get
                Return ResourceManager.GetString("PdfShowPDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Target file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfTargetFile() As String
            Get
                Return ResourceManager.GetString("PdfTargetFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Generate PDF file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfTitle() As String
            Get
                Return ResourceManager.GetString("PdfTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Enter project name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProjectsEnterProjectName() As String
            Get
                Return ResourceManager.GetString("ProjectsEnterProjectName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Projects ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProjectsProject() As String
            Get
                Return ResourceManager.GetString("ProjectsProject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rename project name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProjectsRenameProjectName() As String
            Get
                Return ResourceManager.GetString("ProjectsRenameProjectName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Project adminstration ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProjectsTitle() As String
            Get
                Return ResourceManager.GetString("ProjectsTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Canceled with error ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementCanceledWithError() As String
            Get
                Return ResourceManager.GetString("ReplacementCanceledWithError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Copy files ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementCopyFiles() As String
            Get
                Return ResourceManager.GetString("ReplacementCopyFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Customer extension ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementCustomerExtension() As String
            Get
                Return ResourceManager.GetString("ReplacementCustomerExtension", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Documentation finished ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementDocumentationFinished() As String
            Get
                Return ResourceManager.GetString("ReplacementDocumentationFinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Documentation started ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementDocumentationStarted() As String
            Get
                Return ResourceManager.GetString("ReplacementDocumentationStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No dataset folder selected ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementNoDatasetFolderSelcted() As String
            Get
                Return ResourceManager.GetString("ReplacementNoDatasetFolderSelcted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Orginal ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementOriginal() As String
            Get
                Return ResourceManager.GetString("ReplacementOriginal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die File with replacements ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementReplacementFile() As String
            Get
                Return ResourceManager.GetString("ReplacementReplacementFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Replacing finished ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementReplacingFinished() As String
            Get
                Return ResourceManager.GetString("ReplacementReplacingFinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Replacing started ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementReplacingStarted() As String
            Get
                Return ResourceManager.GetString("ReplacementReplacingStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Target folder ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementTargetFolder() As String
            Get
                Return ResourceManager.GetString("ReplacementTargetFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Replacement of PBIP BIM stucture ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementTitle() As String
            Get
                Return ResourceManager.GetString("ReplacementTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die From ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RFFrom() As String
            Get
                Return ResourceManager.GetString("RFFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RFName() As String
            Get
                Return ResourceManager.GetString("RFName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Edit replacement file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RFTitle() As String
            Get
                Return ResourceManager.GetString("RFTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die To ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RFTo() As String
            Get
                Return ResourceManager.GetString("RFTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SettingsLanguage() As String
            Get
                Return ResourceManager.GetString("SettingsLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The application needs as restart to apply the language settings. Do you want to restart? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SettingsRestart() As String
            Get
                Return ResourceManager.GetString("SettingsRestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SettingsTitle() As String
            Get
                Return ResourceManager.GetString("SettingsTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Replacement of PBIP TDML stucture ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TDMLTitle() As String
            Get
                Return ResourceManager.GetString("TDMLTitle", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
