'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ResourcesLang
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("inoPBI.ResourcesLang", GetType(ResourcesLang).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnCancel() As String
            Get
                Return ResourceManager.GetString("BtnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Clear filter ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnClearFilter() As String
            Get
                Return ResourceManager.GetString("BtnClearFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnClose() As String
            Get
                Return ResourceManager.GetString("BtnClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Create Documentation ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnCreateDokumentation() As String
            Get
                Return ResourceManager.GetString("BtnCreateDokumentation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Create PDF ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnCreatePDF() As String
            Get
                Return ResourceManager.GetString("BtnCreatePDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Delete entry ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnDeleteEntry() As String
            Get
                Return ResourceManager.GetString("BtnDeleteEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Delete selected files ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnDeleteSelectedFiles() As String
            Get
                Return ResourceManager.GetString("BtnDeleteSelectedFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Down ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnDown() As String
            Get
                Return ResourceManager.GetString("BtnDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnEdit() As String
            Get
                Return ResourceManager.GetString("BtnEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnNew() As String
            Get
                Return ResourceManager.GetString("BtnNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die New project ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnNewProject() As String
            Get
                Return ResourceManager.GetString("BtnNewProject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnOK() As String
            Get
                Return ResourceManager.GetString("BtnOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnOpen() As String
            Get
                Return ResourceManager.GetString("BtnOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Refresh ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnRefresh() As String
            Get
                Return ResourceManager.GetString("BtnRefresh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rename project ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnRenameProject() As String
            Get
                Return ResourceManager.GetString("BtnRenameProject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Replace ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnReplace() As String
            Get
                Return ResourceManager.GetString("BtnReplace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnSave() As String
            Get
                Return ResourceManager.GetString("BtnSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Save as ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnSaveAs() As String
            Get
                Return ResourceManager.GetString("BtnSaveAs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Select project ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnSelectProject() As String
            Get
                Return ResourceManager.GetString("BtnSelectProject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Up ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnUp() As String
            Get
                Return ResourceManager.GetString("BtnUp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Backup files for {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CleanupBackupFiles() As String
            Get
                Return ResourceManager.GetString("CleanupBackupFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Do you want to delete {0} selected file(s)? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CleanupDleteFilesQuestion() As String
            Get
                Return ResourceManager.GetString("CleanupDleteFilesQuestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0} file(s) deleted. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CleanupFilesDeleted() As String
            Get
                Return ResourceManager.GetString("CleanupFilesDeleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nothing to do ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CleanupNothingToDo() As String
            Get
                Return ResourceManager.GetString("CleanupNothingToDo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cleanup ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CleanupTitle() As String
            Get
                Return ResourceManager.GetString("CleanupTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Edit file {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property HtmlEditTitle() As String
            Get
                Return ResourceManager.GetString("HtmlEditTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Edit HTML file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property HtmlTitle() As String
            Get
                Return ResourceManager.GetString("HtmlTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Copyright  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InfoCopyright() As String
            Get
                Return ResourceManager.GetString("InfoCopyright", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Info {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InfoTitle() As String
            Get
                Return ResourceManager.GetString("InfoTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Version {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InfoVersion() As String
            Get
                Return ResourceManager.GetString("InfoVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Arrange icons ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainArrangeIcons() As String
            Get
                Return ResourceManager.GetString("MainArrangeIcons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cascade ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainCascade() As String
            Get
                Return ResourceManager.GetString("MainCascade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Close all ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainCloseAll() As String
            Get
                Return ResourceManager.GetString("MainCloseAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Documentation ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainDocumentation() As String
            Get
                Return ResourceManager.GetString("MainDocumentation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Edit Footer/Header ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainEditFooterHeader() As String
            Get
                Return ResourceManager.GetString("MainEditFooterHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainFile() As String
            Get
                Return ResourceManager.GetString("MainFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainHelp() As String
            Get
                Return ResourceManager.GetString("MainHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainInfo() As String
            Get
                Return ResourceManager.GetString("MainInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die New Window ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainNewWindow() As String
            Get
                Return ResourceManager.GetString("MainNewWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Power BI Tools ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainPowerBITools() As String
            Get
                Return ResourceManager.GetString("MainPowerBITools", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Quit ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainQuit() As String
            Get
                Return ResourceManager.GetString("MainQuit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Replacement BIM ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainReplaceBIM() As String
            Get
                Return ResourceManager.GetString("MainReplaceBIM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Replacement Report ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainReplaceReport() As String
            Get
                Return ResourceManager.GetString("MainReplaceReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Replacement TMDL ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainReplaceTDML() As String
            Get
                Return ResourceManager.GetString("MainReplaceTDML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Select Project ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainSelectProject() As String
            Get
                Return ResourceManager.GetString("MainSelectProject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainSettings() As String
            Get
                Return ResourceManager.GetString("MainSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatus() As String
            Get
                Return ResourceManager.GetString("MainStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tile horizontal ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainTileHorizontal() As String
            Get
                Return ResourceManager.GetString("MainTileHorizontal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tile vertical ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainTileVertical() As String
            Get
                Return ResourceManager.GetString("MainTileVertical", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tools ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainTools() As String
            Get
                Return ResourceManager.GetString("MainTools", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Current project: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainTslCurrentProject() As String
            Get
                Return ResourceManager.GetString("MainTslCurrentProject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Usage of measure ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainUsage() As String
            Get
                Return ResourceManager.GetString("MainUsage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Windows ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainWindows() As String
            Get
                Return ResourceManager.GetString("MainWindows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Action is canceled. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgActionIsCanceled() As String
            Get
                Return ResourceManager.GetString("MsgActionIsCanceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Delete selected entry? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgDeleteSelectedEntry() As String
            Get
                Return ResourceManager.GetString("MsgDeleteSelectedEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Entry exists. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgEntryExists() As String
            Get
                Return ResourceManager.GetString("MsgEntryExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die From is missing. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgFromIsMissing() As String
            Get
                Return ResourceManager.GetString("MsgFromIsMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hint ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgHint() As String
            Get
                Return ResourceManager.GetString("MsgHint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No file given. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgNoFileGiven() As String
            Get
                Return ResourceManager.GetString("MsgNoFileGiven", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nothing selected ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgNothingSelected() As String
            Get
                Return ResourceManager.GetString("MsgNothingSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die PDF file in use. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgPdfFileInUse() As String
            Get
                Return ResourceManager.GetString("MsgPdfFileInUse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Something went wrong ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgSomethingWentWrong() As String
            Get
                Return ResourceManager.GetString("MsgSomethingWentWrong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die To is missing. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgToIsMissing() As String
            Get
                Return ResourceManager.GetString("MsgToIsMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Filter Measure ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MUFilterMeasure() As String
            Get
                Return ResourceManager.GetString("MUFilterMeasure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  (hidden) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MUHidden() As String
            Get
                Return ResourceManager.GetString("MUHidden", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die hidden only ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MUHiddenOnly() As String
            Get
                Return ResourceManager.GetString("MUHiddenOnly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Measure ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MUMeasure() As String
            Get
                Return ResourceManager.GetString("MUMeasure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MUName() As String
            Get
                Return ResourceManager.GetString("MUName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Page ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MUPage() As String
            Get
                Return ResourceManager.GetString("MUPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Table ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MUTable() As String
            Get
                Return ResourceManager.GetString("MUTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Measure usage ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MUTitle() As String
            Get
                Return ResourceManager.GetString("MUTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Usage ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MUUsage() As String
            Get
                Return ResourceManager.GetString("MUUsage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Documentation export finished ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfDocumentationExportFinished() As String
            Get
                Return ResourceManager.GetString("PdfDocumentationExportFinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Documentation export to pdf ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfDocumentationExportToPdf() As String
            Get
                Return ResourceManager.GetString("PdfDocumentationExportToPdf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Documentation file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfDocumentationFile() As String
            Get
                Return ResourceManager.GetString("PdfDocumentationFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Document title ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfDocumentTitle() As String
            Get
                Return ResourceManager.GetString("PdfDocumentTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Footer HTML file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfFooterFile() As String
            Get
                Return ResourceManager.GetString("PdfFooterFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Header HTML file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfHeaderFile() As String
            Get
                Return ResourceManager.GetString("PdfHeaderFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Select Footer File ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfSelectFooterFile() As String
            Get
                Return ResourceManager.GetString("PdfSelectFooterFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Select Header file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfSelectHeaderFile() As String
            Get
                Return ResourceManager.GetString("PdfSelectHeaderFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Show PDF file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfShowPDF() As String
            Get
                Return ResourceManager.GetString("PdfShowPDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Target file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfTargetFile() As String
            Get
                Return ResourceManager.GetString("PdfTargetFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Generate PDF file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfTitle() As String
            Get
                Return ResourceManager.GetString("PdfTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Enter project name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProjectsEnterProjectName() As String
            Get
                Return ResourceManager.GetString("ProjectsEnterProjectName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Projects ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProjectsProject() As String
            Get
                Return ResourceManager.GetString("ProjectsProject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rename project name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProjectsRenameProjectName() As String
            Get
                Return ResourceManager.GetString("ProjectsRenameProjectName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Project adminstration ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProjectsTitle() As String
            Get
                Return ResourceManager.GetString("ProjectsTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Define element ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property REDefineElement() As String
            Get
                Return ResourceManager.GetString("REDefineElement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Height ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property REHeight() As String
            Get
                Return ResourceManager.GetString("REHeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Canceled with error ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementCanceledWithError() As String
            Get
                Return ResourceManager.GetString("ReplacementCanceledWithError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Choose folder of Semantic Model ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementChooseFolderOfSemanticModel() As String
            Get
                Return ResourceManager.GetString("ReplacementChooseFolderOfSemanticModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Copy files ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementCopyFiles() As String
            Get
                Return ResourceManager.GetString("ReplacementCopyFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Customer extension ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementCustomerExtension() As String
            Get
                Return ResourceManager.GetString("ReplacementCustomerExtension", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Documentation finished ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementDocumentationFinished() As String
            Get
                Return ResourceManager.GetString("ReplacementDocumentationFinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Documentation started ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementDocumentationStarted() As String
            Get
                Return ResourceManager.GetString("ReplacementDocumentationStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0} Columns to {1}: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementMDColumnHeader() As String
            Get
                Return ResourceManager.GetString("ReplacementMDColumnHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No dataset folder selected ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementNoDatasetFolderSelected() As String
            Get
                Return ResourceManager.GetString("ReplacementNoDatasetFolderSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Orginal ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementOriginal() As String
            Get
                Return ResourceManager.GetString("ReplacementOriginal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0} replacement(s) could not be resolved. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementReplacementError() As String
            Get
                Return ResourceManager.GetString("ReplacementReplacementError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die File with replacements ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementReplacementFile() As String
            Get
                Return ResourceManager.GetString("ReplacementReplacementFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Replacing finished ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementReplacingFinished() As String
            Get
                Return ResourceManager.GetString("ReplacementReplacingFinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Replacing started ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementReplacingStarted() As String
            Get
                Return ResourceManager.GetString("ReplacementReplacingStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Backup file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementReportBackup() As String
            Get
                Return ResourceManager.GetString("ReplacementReportBackup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Report file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementReportOriginal() As String
            Get
                Return ResourceManager.GetString("ReplacementReportOriginal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Page name part ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementReportPage() As String
            Get
                Return ResourceManager.GetString("ReplacementReportPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Replacement 1 ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementReportReplace1() As String
            Get
                Return ResourceManager.GetString("ReplacementReportReplace1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Replacement 2 ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementReportReplace2() As String
            Get
                Return ResourceManager.GetString("ReplacementReportReplace2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Replace of filter ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementReportTitle() As String
            Get
                Return ResourceManager.GetString("ReplacementReportTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Visual type name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementReportVisual() As String
            Get
                Return ResourceManager.GetString("ReplacementReportVisual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Target folder ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementTargetFolder() As String
            Get
                Return ResourceManager.GetString("ReplacementTargetFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Replacement of PBIP BIM stucture ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReplacementTitle() As String
            Get
                Return ResourceManager.GetString("ReplacementTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Width ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property REWidth() As String
            Get
                Return ResourceManager.GetString("REWidth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die X (horizontal) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property REXHorizontal() As String
            Get
                Return ResourceManager.GetString("REXHorizontal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Y (vertical) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property REYVertical() As String
            Get
                Return ResourceManager.GetString("REYVertical", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Allowed difference ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RFAllowedDifference() As String
            Get
                Return ResourceManager.GetString("RFAllowedDifference", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die From ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RFFrom() As String
            Get
                Return ResourceManager.GetString("RFFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RFName() As String
            Get
                Return ResourceManager.GetString("RFName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Edit replacement file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RFTitle() As String
            Get
                Return ResourceManager.GetString("RFTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die To ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RFTo() As String
            Get
                Return ResourceManager.GetString("RFTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RFType() As String
            Get
                Return ResourceManager.GetString("RFType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SettingsLanguage() As String
            Get
                Return ResourceManager.GetString("SettingsLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The application needs as restart to apply the language settings. Do you want to restart? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SettingsRestart() As String
            Get
                Return ResourceManager.GetString("SettingsRestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SettingsTitle() As String
            Get
                Return ResourceManager.GetString("SettingsTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Replacement of PBIP TDML stucture ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TDMLTitle() As String
            Get
                Return ResourceManager.GetString("TDMLTitle", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
