'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ResourcesLang
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("inoPBI.ResourcesLang", GetType(ResourcesLang).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnCancel() As String
            Get
                Return ResourceManager.GetString("BtnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnClose() As String
            Get
                Return ResourceManager.GetString("BtnClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Create PDF ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnCreatePDF() As String
            Get
                Return ResourceManager.GetString("BtnCreatePDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnEdit() As String
            Get
                Return ResourceManager.GetString("BtnEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die New project ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnNewProject() As String
            Get
                Return ResourceManager.GetString("BtnNewProject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnOK() As String
            Get
                Return ResourceManager.GetString("BtnOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rename project ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnRenameProject() As String
            Get
                Return ResourceManager.GetString("BtnRenameProject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnSave() As String
            Get
                Return ResourceManager.GetString("BtnSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Select project ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnSelectProject() As String
            Get
                Return ResourceManager.GetString("BtnSelectProject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Current project: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainTslCurrentProject() As String
            Get
                Return ResourceManager.GetString("MainTslCurrentProject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hint ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgHint() As String
            Get
                Return ResourceManager.GetString("MsgHint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No file given. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgNoFileGiven() As String
            Get
                Return ResourceManager.GetString("MsgNoFileGiven", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nothing selected ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgNothingSelected() As String
            Get
                Return ResourceManager.GetString("MsgNothingSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die PDF file in use. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgPdfFileInUse() As String
            Get
                Return ResourceManager.GetString("MsgPdfFileInUse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Documentation export finished ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfDocumentationExportFinished() As String
            Get
                Return ResourceManager.GetString("PdfDocumentationExportFinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Documentation export to pdf ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfDocumentationExportToPdf() As String
            Get
                Return ResourceManager.GetString("PdfDocumentationExportToPdf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Documentation file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfDocumentationFile() As String
            Get
                Return ResourceManager.GetString("PdfDocumentationFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Document title ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfDocumentTitle() As String
            Get
                Return ResourceManager.GetString("PdfDocumentTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Footer HTML file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfFooterFile() As String
            Get
                Return ResourceManager.GetString("PdfFooterFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Header HTML file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfHeaderFile() As String
            Get
                Return ResourceManager.GetString("PdfHeaderFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Select Footer File ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfSelectFooterFile() As String
            Get
                Return ResourceManager.GetString("PdfSelectFooterFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Select Header file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfSelectHeaderFile() As String
            Get
                Return ResourceManager.GetString("PdfSelectHeaderFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Show PDF file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfShowPDF() As String
            Get
                Return ResourceManager.GetString("PdfShowPDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Target file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfTargetFile() As String
            Get
                Return ResourceManager.GetString("PdfTargetFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Generate PDF file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PdfTitle() As String
            Get
                Return ResourceManager.GetString("PdfTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Enter project name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProjectsEnterProjectName() As String
            Get
                Return ResourceManager.GetString("ProjectsEnterProjectName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Projects ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProjectsProject() As String
            Get
                Return ResourceManager.GetString("ProjectsProject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rename project name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProjectsRenameProjectName() As String
            Get
                Return ResourceManager.GetString("ProjectsRenameProjectName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Project adminstration ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProjectsTitle() As String
            Get
                Return ResourceManager.GetString("ProjectsTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SettingsLanguage() As String
            Get
                Return ResourceManager.GetString("SettingsLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The application needs as restart to apply the language settings. Do you want to restart? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SettingsRestart() As String
            Get
                Return ResourceManager.GetString("SettingsRestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SettingsTitle() As String
            Get
                Return ResourceManager.GetString("SettingsTitle", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
